// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnDja3LquH0kj6VyFkA7aH_dnmo7fJW0',
    appId: '1:875881748415:web:98d711603d9ee76545b30a',
    messagingSenderId: '875881748415',
    projectId: 'sonoflightsoftware',
    authDomain: 'sonoflightsoftware.firebaseapp.com',
    storageBucket: 'sonoflightsoftware.appspot.com',
    measurementId: 'G-0QT7XE8TX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'You need your key for using',
    appId: '1:875881748415:android:ee1a4ea3a84ec1e545b30a',
    messagingSenderId: '875881748415',
    projectId: 'sonoflightsoftware',
    storageBucket: 'sonoflightsoftware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLwMd-13mYh_41pE_BW0TL3ZPUWVqf8ys',
    appId: '1:875881748415:ios:26438436ceff1e6645b30a',
    messagingSenderId: '875881748415',
    projectId: 'sonoflightsoftware',
    storageBucket: 'sonoflightsoftware.appspot.com',
    iosBundleId: 'com.somethingprojectthataymade.sonoflightsoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLwMd-13mYh_41pE_BW0TL3ZPUWVqf8ys',
    appId: '1:875881748415:ios:edb4d493b62c401545b30a',
    messagingSenderId: '875881748415',
    projectId: 'sonoflightsoftware',
    storageBucket: 'sonoflightsoftware.appspot.com',
    iosBundleId: 'com.somethingprojectthataymade.sonoflightsoftware.RunnerTests',
  );
}
